apiVersion: v1
kind: Pod
metadata:
  name: myapachepod1
#  namespace: myapp
spec:
  containers:
  - name: myapachecontainer1
    image: httpd
    resources:
      requests:
        cpu: "0.5"
        memory: "0.5Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
